Create uk_ua.json
Juuxel/WoodsAndMires pull request #15
Opened 2023-04-13 10:59 UTC by unroman

2023-06-25 15:21 UTC, Juuxel requested changes

2023-06-25 15:21 UTC, Juuxel commented on src/main/resources/assets/woods_and_mires/lang/uk_ua.json
> +  "block.suppsquared.woods_and_mires.item_shelf_pine": "Соснова полиця для предметів"
I believe these should rather go into the language files of those mods since the compat isn't provided by WaM.

2023-06-25 18:51 UTC, unroman commented
Minecraft has a bunch of mods that add new types of wood and therefore it is more difficult to control, but if you prefer it, I will add to the mod itself

2023-07-15 20:34 UTC, Juuxel approved these changes
Thanks for the PR!

2023-07-15 20:34 UTC, merged